import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Website of Architects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <main className="px-[8.4375rem] mt-[6.375rem] h-[calc(100vh-6.375rem)] max-h-[calc(100vh-6.375rem)] grid grid-cols-3  font-hoves uppercase">
        <div className="flex flex-col  my-auto">
          <h3 className="text-[4rem] leading-[4rem]">
            Project <br />{" "}
            <span className="text-text-secondary font-semibold">Nurtown</span>
          </h3>
          <div className="">buttons here</div>
          <p>01/02</p>
        </div>
        <div className=" col-span-2  bg-first-hero bg-center bg-cover bg-no-repeat"></div>
      </main>

      <footer></footer>
    </div>
  );
}
